### ISSUE TITLE
Setting specific boundaries for parameters

### ISSUE THREAD

**Issue by amgonzalezd** [Reiyan/pflacco#34]
Hi there! 
I was wondering if it is possible to set specific boundaries for the parameters in the data. (For example: for (x1, x2) parameters to have the lower_bound = [0, -5], upper_bound=[1, 5].) Till now, I've just seen that you can set a scalar for the lower and upper bounds of the classical_ela_features functions, but a list is not allowed. 
If it is not possible... is there any plan to implement this in the future? 

Thanks you in advance!!

**Comment by Reiyan** [comment]
Hi,
this should be possible already. If this does not work for specific features please let me know :).
The documentation also tells you how to do it:
![image](https://user-images.githubusercontent.com/5904987/235786229-cb28a631-969a-4a7f-95c4-1ea1f02dcd19.png)

So you can either supply a single float, which is assumed to apply to every problem dimension or a list of length `dim`
For a 2D example, this would then be exactly how you described it in your comment:
`pflacco.classical_ela_features.calculate_ela_local(X, y, f, dim = 2, lower_bound = [0, -5], upper_bound = [1, 5])`.

**Comment by amgonzalezd** [comment]
Thank you for the quick answer!

The methods `pflacco.classical_ela_features.cm_grad(X, y, lower_bound=[0,-5], upper_bound=[1,5])`  and `pflacco.classical_ela_features.cm_conv(X, y, lower_bound=[0,-5], upper_bound=[1,5])` are sadly not working.
I get the following exceptions:
```
File \lib\site-packages\pflacco\classical_ela_features.py:1152, in calculate_cm_grad(X, y, lower_bound, upper_bound, blocks, minimize)
   1149 blocks = _check_blocks_variable(X, dim, blocks)
   1151 if blocks.min() <= 2:
-> 1152       raise ValueError('The cell grad features can only be computed when all dimensions have more than 2 cells.')
   1154 init = X.copy()
   1155 init['y'] = y if minimize == True else -1 * y

ValueError: The cell grad features can only be computed when all dimensions have more than 2 cells.
```
```
982 blocks = _check_blocks_variable(X, dim, blocks)
    983 if blocks.min() <= 2:
--> 984       raise ValueError('The cell convexity features can only be computed when all dimensions have more than 2 cells.')
    985 if cm_conv_fast_k < 0 or cm_conv_fast_k > X.shape[0]:
    986       raise ValueError('cm_conv_fast_k must be in the interval [0, n] where n is the number of observations in X.')

ValueError: The cell convexity features can only be computed when all dimensions have more than 2 cells.
```
other methods like `cm_angle` are working fine with the bounds I've input to the function. 

Thanks a lot!!

**Comment by Reiyan** [comment]
However, your question gave me some ideas for improvement. So thank you!
Note to myself:
- extend documentation to make this more clear
- fail calculation by default for set `block` values which do not satisfy the requirements
- allow `force` argument in function call which bypasses these checks

**Comment by Reiyan** [comment]
@amgonzalezd 
I extended the documentation:
https://pflacco.readthedocs.io/en/latest/cell_mapping.html

Hope that clarifies some things for you.
Can tell you if you used different samples (X,y) to calculate the different CM features?
