### ISSUE TITLE
calculate_nbc throws IndexError when neighbour distances are tied

### ISSUE THREAD

**Issue by UrbanSkv** [Reiyan/pflacco#40]
**Description**

Due to a small bug in the code that handles ties in nearest neighbor selection, the calculate_nbc function will throw `IndexError: invalid index to scalar variable` if ties are encountered.

The issue occurs in the lines 313-326 in classical_ela_features.py, specifically on the final line.

    i = d[d == d.min()].index.to_numpy()
    if len(i) > 1:
          if dist_tie_breaker == 'sample':
                i = np.random.choice(i)
          elif dist_tie_breaker == 'first':
                i = i[0]
          elif dist_tie_breaker == 'last':
                i = i[-1]
          else:
                raise ValueError('Possible tie breaker methods are "sample", "first", and "last"')
  
  
    # Transform array of length 1 to a single scalar
    i = i[0]

Since the code in the if block already transforms i from an array into a single numeric value, the attempt to index i in line 326 will throw an error.

**To Replicate**
Call calculate_nbc on samples that include elements equidistant  from one another
  
    X = [[x,x] for x in range(100)]
    y = [0] * 100
    calculate_nbc(X, y)

**Possible Solution**
Moving the final line into it's own else block so that it's only called when ties aren't present appears to resolve this issue

    i = d[d == d.min()].index.to_numpy()
    if len(i) > 1:
          if dist_tie_breaker == 'sample':
                i = np.random.choice(i)
          elif dist_tie_breaker == 'first':
                i = i[0]
          elif dist_tie_breaker == 'last':
                i = i[-1]
          else:
                raise ValueError('Possible tie breaker methods are "sample", "first", and "last"')
    else:
          # Transform array of length 1 to a single scalar
          i = i[0]

**Comment by Reiyan** [comment]
Hey, thanks for pointing that out.

I will include that fix asap.

**Comment by Reiyan** [comment]
Hey @UrbanSkv,
thanks for pointing that out.

Which version of pflacco did you use? I think I already fixed that one in the past.

**Comment by Reiyan** [comment]
Probably in #14

**Comment by UrbanSkv** [comment]
I'm using version 1.2.1

Looking at the commit history, it seems that this could have been a regression in commit 2611dfe, which added the final line `i = i[0]`

**Comment by Reiyan** [comment]
Damn, you are right. Thanks, will fix asap.

**Comment by Reiyan** [comment]
fixed and published new 1.2.2 version
